# Generated by Django 5.0 on 2023-12-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('N', 'Normal'), ('H', 'Hight'), ('I', 'Inmediate')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('n', 'Not Started'), ('a', 'Assigned'), ('p', 'In Progress'), ('s', 'Stopped'), ('c', 'Canceled'), ('f', 'Finished')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tasks_app.tag'),
        ),
    ]
